### PR TITLE
Remove Unneeded Variables in Squash Deployment

### LINKED ISSUE #136: 0.5.2 docker image can not be pulled
A similar problem that caused #130 recurs.
The 0.5.2 squash docker image cannot be loaded.
It seems that the path of the docker image is still broken.

When I deploy execute following command with squashctl version 0.5.2, 
```bash
squashctl deploy squash
kubectl edit deployment -n squash-debugger
```
the image path in the deploy config was `image: quay.io/solo-io/0.5.2:0.5.2`.
In my thought, it should be `image: quay.io/solo-io/squash:0.5.2`.

Please take a look!

### PR DESCRIPTION
**Pull request by sanha**
**Major changes:**
- Remove unneeded variables (that are overridden by flags at now).

### CODE REVIEW

**Comment by hgword** [comment]
@sanha 
need to check this file.
https://github.com/solo-io/squash/blob/master/Makefile#L22#L24

File: pkg/install/squash.go [hunk 1]
```diff
@@ -30,7 +26,7 @@ var (
 // ClusterRole - enabling pod creation
 // ClusterRoleBinding - bind ClusterRole to Squash's ServiceAccount
 // Deployment - Squash itself
-func InstallSquash(cs *kubernetes.Clientset, namespace, containerRepo, containerVersion string, preview bool) error {
+func InstallSquash(cs *kubernetes.Clientset, namespace, containerRepo, preview bool) error {
```
Comment (hgword) [inline pkg/install/squash.go]: containerRepo --> containerRepo string

Comment (mitchdraft) [reply pkg/install/squash.go]: exactly, as @hgword said:
```suggestion
func InstallSquash(cs *kubernetes.Clientset, namespace, containerRepo string, preview bool) error {
```

File: pkg/install/squash.go [hunk 2]
```diff
@@ -124,7 +120,7 @@ func InstallSquash(cs *kubernetes.Clientset, namespace, containerRepo, container
 					Containers: []v1.Container{
 						{
 							Name:  SquashName,
-							Image: fmt.Sprintf("%v/%v:%v", containerRepo, containerVersion, version.SquashImageTag),
+							Image: fmt.Sprintf("%v/%v:%v", containerRepo, SquashName, version.SquashImageTag),
```
Comment (mitchdraft) [inline pkg/install/squash.go]: This correctly fixes the issue, however we would still like to be able to overwrite the tag from the command line flag, as in https://github.com/solo-io/squash/pull/139
I'm sorry, I did not see your PR before I made the fix, otherwise I would have merged yours

File: pkg/install/squash.go [hunk 3]
```diff
@@ -14,13 +14,9 @@ import (
 )
 
 var (
-	SquashRepoName  = "quay.io/solo-io"
-	SquashName      = "squash"
-	SquashImageName = "squash"
-
+	SquashName    = "squash"
```
Comment (mitchdraft) [inline pkg/install/squash.go]: I'd like to merge this portion of the change if you don't mind rebasing

**Comment by mitchdraft** [comment]
@sanha thank you for addressing this. Before I saw your PR I did the fix on https://github.com/solo-io/squash/pull/139

Still, I'd like to merge your cleanup of the vars in https://github.com/solo-io/squash/pull/137/files/48290d67777384312c71ebf1f251b56f0632a692#diff-f7ed3785f15d52d757d380b0d1dd6e87L17

If you don't mind rebasing and updating this to include just those changes I'll go ahead and merge.

File: pkg/install/squash.go (hunk 2 above)
Comment (sanha) [reply pkg/install/squash.go]: Never mind. It is also a pleasure to see my issue resolved quickly :)

File: pkg/install/squash.go (hunk 3 above)
Comment (sanha) [reply pkg/install/squash.go]: Sure. I'll update this PR.

**Comment by sanha** [comment]
@mitchdraft I updated this PR (including the title and description). Please take a look. Thanks :)
